import type { UserCreateInput, UserUpdateInput } from "../../prisma/src/generated/prisma/models/User.ts";
import type { User } from "../../prisma/src/generated/prisma/client.ts";
declare class UserRepository {
    getUsers(): Promise<{
        id: string;
        name: string;
        surname: string;
        age: number;
        email: string;
        password: string;
        phone: string | null;
        gender: import("../../prisma/src/generated/prisma/enums.ts").GenderEnum | null;
        photo: string | null;
        role_id: number;
        region_id: number;
        city: string;
        account_type: import("../../prisma/src/generated/prisma/enums.ts").AccountTypeEnum;
        balance: number;
        currency: import("../../prisma/src/generated/prisma/enums.ts").CurrencyEnum;
        premium_since: Date | null;
        premium_until: Date | null;
        is_verified: boolean;
        is_active: boolean;
        is_deleted: boolean;
        created_at: Date;
        updated_at: Date;
    }[]>;
    getUserById(id: string): Promise<{
        id: string;
        name: string;
        surname: string;
        age: number;
        email: string;
        password: string;
        phone: string | null;
        gender: import("../../prisma/src/generated/prisma/enums.ts").GenderEnum | null;
        photo: string | null;
        role_id: number;
        region_id: number;
        city: string;
        account_type: import("../../prisma/src/generated/prisma/enums.ts").AccountTypeEnum;
        balance: number;
        currency: import("../../prisma/src/generated/prisma/enums.ts").CurrencyEnum;
        premium_since: Date | null;
        premium_until: Date | null;
        is_verified: boolean;
        is_active: boolean;
        is_deleted: boolean;
        created_at: Date;
        updated_at: Date;
    } | null>;
    getUserByParams(params: Partial<User>): Promise<{
        id: string;
        name: string;
        surname: string;
        age: number;
        email: string;
        password: string;
        phone: string | null;
        gender: import("../../prisma/src/generated/prisma/enums.ts").GenderEnum | null;
        photo: string | null;
        role_id: number;
        region_id: number;
        city: string;
        account_type: import("../../prisma/src/generated/prisma/enums.ts").AccountTypeEnum;
        balance: number;
        currency: import("../../prisma/src/generated/prisma/enums.ts").CurrencyEnum;
        premium_since: Date | null;
        premium_until: Date | null;
        is_verified: boolean;
        is_active: boolean;
        is_deleted: boolean;
        created_at: Date;
        updated_at: Date;
    } | null>;
    createUser(dto: UserCreateInput): Promise<{
        id: string;
        name: string;
        surname: string;
        age: number;
        email: string;
        password: string;
        phone: string | null;
        gender: import("../../prisma/src/generated/prisma/enums.ts").GenderEnum | null;
        photo: string | null;
        role_id: number;
        region_id: number;
        city: string;
        account_type: import("../../prisma/src/generated/prisma/enums.ts").AccountTypeEnum;
        balance: number;
        currency: import("../../prisma/src/generated/prisma/enums.ts").CurrencyEnum;
        premium_since: Date | null;
        premium_until: Date | null;
        is_verified: boolean;
        is_active: boolean;
        is_deleted: boolean;
        created_at: Date;
        updated_at: Date;
    }>;
    updateUserByIdAndParams(id: string, dto: UserUpdateInput): Promise<{
        id: string;
        name: string;
        surname: string;
        age: number;
        email: string;
        password: string;
        phone: string | null;
        gender: import("../../prisma/src/generated/prisma/enums.ts").GenderEnum | null;
        photo: string | null;
        role_id: number;
        region_id: number;
        city: string;
        account_type: import("../../prisma/src/generated/prisma/enums.ts").AccountTypeEnum;
        balance: number;
        currency: import("../../prisma/src/generated/prisma/enums.ts").CurrencyEnum;
        premium_since: Date | null;
        premium_until: Date | null;
        is_verified: boolean;
        is_active: boolean;
        is_deleted: boolean;
        created_at: Date;
        updated_at: Date;
    }>;
    deleteUserById(id: string): Promise<{
        id: string;
        name: string;
        surname: string;
        age: number;
        email: string;
        password: string;
        phone: string | null;
        gender: import("../../prisma/src/generated/prisma/enums.ts").GenderEnum | null;
        photo: string | null;
        role_id: number;
        region_id: number;
        city: string;
        account_type: import("../../prisma/src/generated/prisma/enums.ts").AccountTypeEnum;
        balance: number;
        currency: import("../../prisma/src/generated/prisma/enums.ts").CurrencyEnum;
        premium_since: Date | null;
        premium_until: Date | null;
        is_verified: boolean;
        is_active: boolean;
        is_deleted: boolean;
        created_at: Date;
        updated_at: Date;
    }>;
}
export declare const userRepository: UserRepository;
export {};
//# sourceMappingURL=user.repository.d.ts.map